### ISSUE TITLE
updating result of 3rd semester

### ISSUE THREAD

**Issue by NamanKhurana** [Sid-2D/IPU-Result-Parser#18]

**Comment by NamanKhurana** [comment]
Bro your website is awesome but this time it has not been updated. Can you please look forward to it.

**Comment by Sid-2D** [comment]
Hey @NamanKhurana 

Please take a look here: [https://github.com/Sid-2D/Outcome-IPU/issues/17](https://github.com/Sid-2D/Outcome-IPU/issues/17)

I will update this by tonight.
